spring.application.name=curso-inscripciones-service
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/inscripciones-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.resumenes.local-dir=${RESUMENES_LOCAL_DIR:./resumenes}
app.aws.region=${AWS_REGION:us-east-1}
app.aws.s3.resumenes-bucket=${AWS_S3_RESUMENES_BUCKET:}
