CREATE TABLE IF NOT EXISTS cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    instructor VARCHAR(120) NOT NULL,
    duracion_horas INTEGER NOT NULL CHECK (duracion_horas > 0),
    costo DECIMAL(12, 2) NOT NULL CHECK (costo >= 0)
);

CREATE TABLE IF NOT EXISTS inscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_nombre VARCHAR(120) NOT NULL,
    estudiante_email VARCHAR(160) NOT NULL,
    total DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
    fecha_inscripcion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inscripcion_cursos (
    inscripcion_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    PRIMARY KEY (inscripcion_id, curso_id),
    CONSTRAINT fk_inscripcion_cursos_inscripcion
        FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_inscripcion_cursos_curso
        FOREIGN KEY (curso_id) REFERENCES cursos (id)
);

CREATE TABLE IF NOT EXISTS resumenes_inscripcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id BIGINT NOT NULL UNIQUE,
    nombre_archivo VARCHAR(160) NOT NULL,
    ruta_local VARCHAR(500),
    bucket_s3 VARCHAR(120),
    key_s3 VARCHAR(500),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_subida_s3 TIMESTAMP,
    CONSTRAINT fk_resumenes_inscripcion_inscripcion
        FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_inscripciones_email
    ON inscripciones (estudiante_email);

CREATE INDEX IF NOT EXISTS idx_resumenes_inscripcion_inscripcion_id
    ON resumenes_inscripcion (inscripcion_id);
